[project]
name = "daft-minhash-dedupe"
version = "0.1.0"
description = "Minhash Deduplication Workload over Common Crawl Dataset with Daft"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "daft[aws]",
    "python-dotenv",
    "ipykernel",
]
